#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/utils.js:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/utils.js
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xdc.tci:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xdc.tci
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/template.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/template.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/om2.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/om2.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xmlgen.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xmlgen.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xmlgen2.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/xmlgen2.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/Warnings.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/Warnings.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/IPackage.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/IPackage.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/package.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/package.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/global/Clock.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/global/Clock.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/global/Trace.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/global/Trace.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/bld.js:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/bld.js
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/BuildEnvironment.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/PackageContents.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/PackageContents.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/_gen.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/_gen.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Library.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Library.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Executable.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Executable.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Repository.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Repository.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Configuration.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Configuration.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Script.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Script.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Manifest.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Manifest.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Utils.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/Utils.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget2.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget2.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget3.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITarget3.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/ITargetFilter.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/package.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/bld/package.xs
package.mak: config.bld
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/ITarget.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/ITarget.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/_utils.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/_utils.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/Linux86.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/Linux86.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/Mingw.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/Mingw.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/package.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/package.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/ITarget.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/ITarget.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/GCArmv6.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/GCArmv7A.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/IM.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/IM.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/M3.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/M3.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A8F.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A8F.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A9F.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A9F.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A15F.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A15F.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A53F.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/A53F.xs
/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/package.xs:
package.mak: /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/package.xs
package.mak: package.bld
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/io/File.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/io/File.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/io/package.xs:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/services/io/package.xs
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/dmitrii/ti/ccs910/xdctools_3_55_02_22_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.A15F.rootDir ?= /home/dmitrii/ti/ccs910/ccs/tools/compiler/gcc-arm-none-eabi-7-2017-q4-major
gnu.targets.arm.packageBase ?= /home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oa15fg
.PHONY: all,a15fg .dlls,a15fg .executables,a15fg test,a15fg
all,a15fg: .executables,a15fg
.executables,a15fg: .libraries,a15fg
.executables,a15fg: .dlls,a15fg
.dlls,a15fg: .libraries,a15fg
.libraries,a15fg: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,a15fg
	@$(ECHO) xdc .executables,a15fg
	@$(ECHO) xdc .libraries,a15fg
	@$(ECHO) xdc .dlls,a15fg


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,a15fg .dlls: app.pa15fg

-include package/cfg/app_pa15fg.mak
-include package/cfg/app_pa15fg.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_pa15fg.dep
endif
app.pa15fg: package/cfg/app_pa15fg.xdl
	@


ifeq (,$(wildcard .libraries,a15fg))
app.pa15fg package/cfg/app_pa15fg.c: .libraries,a15fg
endif

package/cfg/app_pa15fg.c package/cfg/app_pa15fg.h package/cfg/app_pa15fg.xdl: override _PROG_NAME := app.xa15fg
package/cfg/app_pa15fg.c package/cfg/app_pa15fg.xdl: override _PROG_XSOPTS = -DBOARD=evmAM572x
package/cfg/app_pa15fg.c: package/cfg/app_pa15fg.cfg
package/cfg/app_pa15fg.xdc.inc: package/cfg/app_pa15fg.xdl
package/cfg/app_pa15fg.xdl package/cfg/app_pa15fg.c: .interfaces

clean:: clean,a15fg
	-$(RM) package/cfg/app_pa15fg.cfg
	-$(RM) package/cfg/app_pa15fg.dep
	-$(RM) package/cfg/app_pa15fg.c
	-$(RM) package/cfg/app_pa15fg.xdc.inc

clean,a15fg::
	-$(RM) app.pa15fg
.executables,a15fg .executables: app.xa15fg

app.xa15fg: |app.pa15fg

-include package/cfg/app.xa15fg.mak
app.xa15fg: package/cfg/app_pa15fg.oa15fg 
	$(RM) $@
	@$(MSG) lnka15fg $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.A15F.rootDir)/bin/arm-none-eabi-gcc -mfloat-abi=hard -nostartfiles -Wl,-static -Wl,--gc-sections    -o $@ package/cfg/app_pa15fg.oa15fg -Wl,-T,package/cfg/app_pa15fg.xdl   -L/home/dmitrii/ti/bios_6_76_02_02/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/lib/hard -Wl,--start-group -lgcc -lc -lm -Wl,--end-group --specs=nano.specs -Wl,-Map=$(XDCCFGDIR)/$@.map --specs=nosys.specs
	
app.xa15fg: export LD_LIBRARY_PATH=

app.test test,a15fg test: app.xa15fg.test

app.xa15fg.test:: app.xa15fg
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xa15fg.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xa15fg, ) 
endif

clean,a15fg::
	-$(RM) $(wildcard .tmp,app.xa15fg,*)


clean:: clean,a15fg

clean,a15fg::
	-$(RM) app.xa15fg
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_pa15fg.oa15fg,copy : package/cfg/app_pa15fg.oa15fg
app_pa15fg.sa15fg,copy : package/cfg/app_pa15fg.sa15fg

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
